name: My first pipeline

on: push

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: chekout code3
        uses: actions/checkout@v4
      - name: Build image
        run : docker build -t Malick100/ciportfolio .
      - name: List images
        run: docker images
      
             
